# ---- Build stage ----
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_MESHCENTRAL_URL
ARG VITE_MESHCENTRAL_AGENT_INVITE_URL
ARG VITE_MESHCENTRAL_MESH_ID
ARG VITE_MESHCENTRAL_AGENT_DOWNLOAD_URL
ARG VITE_MESHCENTRAL_AGENT_WINDOWS_URL
ARG VITE_MESHCENTRAL_AGENT_MAC_INTEL_URL
ARG VITE_MESHCENTRAL_AGENT_MAC_ARM_URL

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_MESHCENTRAL_URL=$VITE_MESHCENTRAL_URL
ENV VITE_MESHCENTRAL_AGENT_INVITE_URL=$VITE_MESHCENTRAL_AGENT_INVITE_URL
ENV VITE_MESHCENTRAL_MESH_ID=$VITE_MESHCENTRAL_MESH_ID
ENV VITE_MESHCENTRAL_AGENT_DOWNLOAD_URL=$VITE_MESHCENTRAL_AGENT_DOWNLOAD_URL
ENV VITE_MESHCENTRAL_AGENT_WINDOWS_URL=$VITE_MESHCENTRAL_AGENT_WINDOWS_URL
ENV VITE_MESHCENTRAL_AGENT_MAC_INTEL_URL=$VITE_MESHCENTRAL_AGENT_MAC_INTEL_URL
ENV VITE_MESHCENTRAL_AGENT_MAC_ARM_URL=$VITE_MESHCENTRAL_AGENT_MAC_ARM_URL

RUN npm run build

# ---- Serve stage ----
FROM nginx:alpine AS serve

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
