# ---- Build stage ----
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_RUSTDESK_ID_SERVER
ARG VITE_RUSTDESK_RELAY_SERVER
ARG VITE_RUSTDESK_KEY
ARG VITE_RUSTDESK_WEB_CLIENT_ENABLED
ARG VITE_RUSTDESK_WEB_CLIENT_URL
ARG VITE_RUSTDESK_WEB_CLIENT_TEMPLATE
ARG VITE_RUSTDESK_DOWNLOAD_WINDOWS_URL
ARG VITE_RUSTDESK_DOWNLOAD_MAC_INTEL_URL
ARG VITE_RUSTDESK_DOWNLOAD_MAC_ARM_URL
ARG VITE_RUSTDESK_DOWNLOAD_LINUX_URL

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_RUSTDESK_ID_SERVER=$VITE_RUSTDESK_ID_SERVER
ENV VITE_RUSTDESK_RELAY_SERVER=$VITE_RUSTDESK_RELAY_SERVER
ENV VITE_RUSTDESK_KEY=$VITE_RUSTDESK_KEY
ENV VITE_RUSTDESK_WEB_CLIENT_ENABLED=$VITE_RUSTDESK_WEB_CLIENT_ENABLED
ENV VITE_RUSTDESK_WEB_CLIENT_URL=$VITE_RUSTDESK_WEB_CLIENT_URL
ENV VITE_RUSTDESK_WEB_CLIENT_TEMPLATE=$VITE_RUSTDESK_WEB_CLIENT_TEMPLATE
ENV VITE_RUSTDESK_DOWNLOAD_WINDOWS_URL=$VITE_RUSTDESK_DOWNLOAD_WINDOWS_URL
ENV VITE_RUSTDESK_DOWNLOAD_MAC_INTEL_URL=$VITE_RUSTDESK_DOWNLOAD_MAC_INTEL_URL
ENV VITE_RUSTDESK_DOWNLOAD_MAC_ARM_URL=$VITE_RUSTDESK_DOWNLOAD_MAC_ARM_URL
ENV VITE_RUSTDESK_DOWNLOAD_LINUX_URL=$VITE_RUSTDESK_DOWNLOAD_LINUX_URL

RUN npm run build

# ---- Serve stage ----
FROM nginx:alpine AS serve

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
